language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t adnenehamdouni/my-react-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true adnenehamdouni/my-react-docker-app npm run test

after_success:
  - docker build -t indreklasn/my-react-docker-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adnenehamdouni/my-react-docker-app