version: "3.8"
services:
  client:
    container_name: react-sample-app
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"